apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: odhservicemonitor
  labels:
    team: opendatahub
spec:
  selector: {}
  endpoints:
    - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: opendatahub
  name: kafkaservicemonitor
spec:
  endpoints:
    - port: prometheus
  selector: {}
