apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jupyterhub
        component.opendatahub.io/name: jupyterhub
        opendatahub.io/component: 'true'
      annotations:
        sidecar.istio.io/inject: "true"
      name: jupyterhub-db
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: jupyterhub
              key: POSTGRESQL_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jupyterhub
              key: POSTGRESQL_PASSWORD
        - name: POSTGRESQL_DATABASE
          value: jupyterhub
        livenessProbe:
          tcpSocket:
            port: 5432
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
              'SELECT 1'
        resources:
          limits:
            memory: 1Gi
            cpu: 1
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: data
        image: centos/postgresql-96-centos7:latest
        imagePullPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: jupyterhub-db
      - configMap:
          defaultMode: 420
          name: jupyterhub-cfg
        name: config
