
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- minimal-notebook-imagestream.yaml
- scipy-notebook-imagestream.yaml
- tensorflow-notebook-imagestream.yaml
- spark-scipy-notebook-imagestream.yaml
- elyra-notebook-imagestream.yaml
commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub
patchesJson6902:
- target:
    group: image.openshift.io
    kind: ImageStream
    version: v1
    name: nbviewer
  path: nbviewer-imagestream.yaml
- target:
    group: image.openshift.io
    kind: ImageStream
    version: v1
    name: s2i-spark-minimal-notebook
  path: spark-notebook-imagestream.yaml
