apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: PostgreSQL
    openshift.io/image.dockerRepositoryCheck: "2020-09-25T11:04:02Z"
    samples.operator.openshift.io/version: 4.5.0-0.okd-2020-09-04-180756
  creationTimestamp: null
  generation: 1
  labels:
    samples.operator.openshift.io/managed: "false"
  name: postgresql
  namespace: openshift
  selfLink: /apis/image.openshift.io/v1/namespaces/openshift/imagestreams/postgresql
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Provides a PostgreSQL 10 database on CentOS 7. For more information
        about using this database image, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/blob/master/README.md.
      iconClass: icon-postgresql
      openshift.io/display-name: PostgreSQL (Ephemeral) 10
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: database,postgresql
      version: "10"
    from:
      kind: DockerImage
      name: --LOCAL_REGISTRY--/centos/postgresql-10-centos7:latest
    generation: 1
    importPolicy: {}
    name: "10"
    referencePolicy:
      type: Local
  - annotations:
      description: Provides a PostgreSQL 12 database on CentOS 7. For more information
        about using this database image, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/blob/master/README.md.
      iconClass: icon-postgresql
      openshift.io/display-name: PostgreSQL (Ephemeral) 12
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: database,postgresql
      version: "12"
    from:
      kind: DockerImage
      name: --LOCAL_REGISTRY--/centos/postgresql-12-centos7:latest
    generation: 1
    importPolicy: {}
    name: "12"
    referencePolicy:
      type: Local
  - annotations:
      description: Provides a PostgreSQL 9.6 database on CentOS 7. For more information
        about using this database image, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/blob/master/README.md.
      iconClass: icon-postgresql
      openshift.io/display-name: PostgreSQL (Ephemeral) 9.6
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: database,postgresql
      version: "9.6"
    from:
      kind: DockerImage
      name: --LOCAL_REGISTRY--/centos/postgresql-96-centos7:latest
    generation: 1
    importPolicy: {}
    name: "9.6"
    referencePolicy:
      type: Local
  - annotations:
      description: |-
        Provides a PostgreSQL database on CentOS 7. For more information about using this database image, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/blob/master/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of PostgreSQL available on OpenShift, including major version updates.
      iconClass: icon-postgresql
      openshift.io/display-name: PostgreSQL (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: database,postgresql
    from:
      kind: ImageStreamTag
      name: "12"
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local
