apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    techPreviewUserWorkload:
      enabled: true
    prometheusK8s:
      retention: 72h
      volumeClaimTemplate:
        metadata:
          name: prometheusK8s
        spec:
          storageClassName: rook-ceph-block
          resources:
            requests:
              storage: 20Gi