kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-openshift
  namespace: openshift-serverless
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - knative-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - operator.knative.dev
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-openshift
  namespace: openshift-serverless
subjects:
- kind: ServiceAccount
  name: knative-openshift
roleRef:
  kind: Role
  name: knative-openshift
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: knative-openshift
rules:
  - apiGroups: 
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-openshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knative-openshift
subjects:
- kind: ServiceAccount
  name: knative-openshift
  namespace: openshift-serverless
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-openshift
  namespace: openshift-serverless
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: knative-serving-prometheus-k8s
  namespace: openshift-monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knative-serving-prometheus-k8s
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knative-serving-prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: knative-openshift-ingress
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - events
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - networking.internal.knative.dev
  resources:
  - clusteringresses
  - clusteringresses/status
  - clusteringresses/finalizers
  - ingresses
  - ingresses/status
  - ingresses/finalizers
  verbs:
  - "*"
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  - routes/status
  - routes/finalizers
  verbs:
  - "*"
- apiGroups:
  - operator.knative.dev
  resources:
  - knativeservings
  - knativeservings/finalizers
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-openshift-ingress
  namespace: openshift-serverless
subjects:
- kind: ServiceAccount
  name: knative-openshift-ingress
  namespace: openshift-serverless
roleRef:
  kind: ClusterRole
  name: knative-openshift-ingress
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-openshift-ingress
  namespace: openshift-serverless
