
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#resources:
patchesJson6902:
- target:
    group: apps.openshift.io
    kind: DeploymentConfig
    version: v1
    name: jupyterhub
  path: jupyterhub-dc.yaml
- target:
    kind: PersistentVolumeClaim
    version: v1
    name: jupyterhub-db
  path: jupyterhub-db-pvc.yaml
- target:
    kind: ConfigMap
    version: v1
    name: jupyterhub-cfg
  path: jupyterhub-configmap.yaml
- target:
    kind: ConfigMap
    version: v1
    name: jupyter-singleuser-profiles
  path: jupyterhub-singleuser-profiles-configmap.yaml
- target:
    group: image.openshift.io
    kind: ImageStream
    version: v1
    name: jupyterhub-img
  path: jupyterhub-img-imagestream.yaml
