
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#resources:
patchesJson6902:
- target:
    group: apps
    kind: Deployment
    version: v1
    name: jupyterhub-db
  path: jupyterhub-db-deployment.yaml
- target:
    group: apps
    kind: Deployment
    version: v1
    name: jupyterhub
  path: jupyterhub-deployment.yaml
- target:
    kind: PersistentVolumeClaim
    version: v1
    name: jupyterhub-db
  path: jupyterhub-db-pvc.yaml
- target:
    kind: ConfigMap
    version: v1
    name: jupyterhub-cfg
  path: jupyterhub-configmap.yaml
